library("xtable")
library("dplyr")
library("data.table")
library("shiny")
library("Biostrings")
library("tidyverse")
library("knitr")
library("kableExtra")
library("readxl")
library("DECIPHER")
library("ranger")
library("muscle")
library("DT")

setwd("~/Documents/Wageningen_UR/github/pallas/shiny_app/")
source("src/extract_34_aa_loop.r")
# sqs <- readAAStringSet("~/Downloads/Lysines.faa")
sqs <- readAAStringSet("~/Downloads/Lysines.faa")
query_fils <- sapply(1:length(sqs), function(x) {tempfile(pattern = "", fileext = ".fasta")})
sapply(1:length(sqs), function(x) {writeXStringSet(sqs[x], query_fils[x])})
source("src/extract_34_aa_loop.R")
extract_34_list <- lapply(1:length(sqs), function(x) { extract_34_aa_loop(query_fils[x]) })
extract_34_df <- data.frame(matrix(unlist(extract_34_list), nrow = length(extract_34_list), byrow=T), 
                            stringsAsFactors=FALSE)
colnames(extract_34_df)[1:510] <- as.character(fread("data/feature_names.txt", data.table = F)[,1])

write_csv(extract_34_df, "output/test_extracted.csv")